export const API_ROUTES = {
  // Auth
  AUTH: {
    LOGIN: '/api/auth/login',
    LOGOUT: '/api/auth/logout',
    CALLBACK: '/api/auth/callback',
    ME: '/api/auth/me',
  },
  // Content
  CLASSES: '/api/classes',
  SUBJECTS: '/api/subjects',
  CHAPTERS: '/api/chapters',
  LECTURES: '/api/lectures',
  MCQ: '/api/mcq',
  CQ: '/api/cq',
  BOARD_QUESTIONS: '/api/board-questions',
  BOARD_YEARS: '/api/board-years',
  BANNERS: '/api/banners',
  NOTICES: '/api/notices',
  SUGGESTIONS: '/api/suggestions',
  EXAMS: '/api/exams',
  FAQS: '/api/faqs',
  TESTIMONIALS: '/api/testimonials',
  SEARCH: '/api/search',
  STATS: '/api/stats',
  CONFIG: '/api/config',
  CONTENT_TYPES: '/api/content-types',
  // Payment
  PAYMENT: {
    CREATE: '/api/payment/create',
    CHECK: '/api/payment/check',
    BATCH_CHECK: '/api/payment/batch-check',
    ACCOUNTS: '/api/payment/accounts',
    CONTENT_INFO: '/api/payment/content-info',
  },
  // Admin
  ADMIN: {
    CLASSES: '/api/admin/classes',
    SUBJECTS: '/api/admin/subjects',
    CHAPTERS: '/api/admin/chapters',
    TOPICS: '/api/admin/topics',
    MCQ: '/api/admin/mcq',
    CQ: '/api/admin/cq',
    LECTURES: '/api/admin/lectures',
    BANNERS: '/api/admin/banners',
    NOTICES: '/api/admin/notices',
    SUGGESTIONS: '/api/admin/suggestions',
    EXAMS: '/api/admin/exams',
    BULLETINS: '/api/admin/bulletins',
    USERS: '/api/admin/users',
    STATS: '/api/admin/stats',
    BUNDLES: '/api/admin/bundles',
    PACKAGES: '/api/admin/packages',
    FEATURED: '/api/admin/featured',
    BULK_IMPORT: '/api/admin/bulk-import',
    SETTINGS: '/api/admin/settings',
    BOARD: '/api/admin/board',
    BOARD_YEARS: '/api/admin/board-years',
    PAYMENTS: '/api/admin/payments',
    CONTENT_TYPES: '/api/admin/content-types',
    CONTENT_HIERARCHY: '/api/admin/content-hierarchy',
    PERMISSIONS: '/api/admin/permissions',
    SUBSCRIPTIONS: '/api/admin/subscriptions',
    TESTIMONIALS: '/api/admin/testimonials',
    FAQS: '/api/admin/faqs',
    CONTENT: '/api/admin/content',
    NOTIFICATIONS: '/api/admin/notifications',
    MCQ_EXAM_PACKAGES: '/api/admin/mcq-exam-packages',
    CQ_EXAM_PACKAGES: '/api/admin/cq-exam-packages',
    COURSES: '/api/admin/courses',
  },
  // User
  USER: {
    PROFILE: '/api/user/profile',
    DASHBOARD: '/api/user/dashboard',
  },
  // Content
  NOTES: '/api/notes',
  BOOKMARKS: '/api/bookmarks',
  PROGRESS: '/api/progress',
  RECENTLY_VIEWED: '/api/recently-viewed',
  FEEDBACK: '/api/user/feedback',
  // MCQ/CQ Exams
  MCQ_EXAM_PACKAGES: '/api/mcq-exam-packages',
  CQ_EXAM_PACKAGES: '/api/cq-exam-packages',
  COURSES: '/api/courses',
  // Hierarchies
  HIERARCHY_METADATA: '/api/hierarchy/metadata',
  // CSRF
  CSRF_TOKEN: '/api/csrf-token',
  // Upload
  UPLOADTHING: '/api/uploadthing',
} as const

export type ApiRouteValue = typeof API_ROUTES[keyof typeof API_ROUTES] | typeof API_ROUTES.AUTH[keyof typeof API_ROUTES.AUTH] | typeof API_ROUTES.PAYMENT[keyof typeof API_ROUTES.PAYMENT] | typeof API_ROUTES.ADMIN[keyof typeof API_ROUTES.ADMIN] | typeof API_ROUTES.USER[keyof typeof API_ROUTES.USER]
