export const queryKeys = {
  config: ['config'] as const,
  stats: ['stats'] as const,
  faqs: ['faqs'] as const,
  testimonials: ['testimonials'] as const,
  teachers: ['teacher-moderators'] as const,
  boards: ['boards'] as const,
  years: ['years'] as const,
  hierarchyMetadata: ['hierarchy', 'metadata'] as const,
  banners: ['banners'] as const,
  notices: ['notices'] as const,
  classes: ['classes'] as const,
  featuredCourses: ['courses', 'featured'] as const,
  boardQuestionFilters: ['board-questions', 'filters'] as const,
  premiumPrices: ['premium', 'prices'] as const,
  courses: (params?: Record<string, unknown>) =>
    ['courses', params] as const,
  courseDetail: (slug: string) =>
    ['course', slug] as const,
  coursePurchases: () =>
    ['course-purchases'] as const,
  analytics: {
    revenue: (params?: Record<string, unknown>) => ['analytics', 'revenue', params] as const,
    students: (params?: Record<string, unknown>) => ['analytics', 'students', params] as const,
    retention: (params?: Record<string, unknown>) => ['analytics', 'retention', params] as const,
    conversion: (params?: Record<string, unknown>) => ['analytics', 'conversion', params] as const,
    dropoff: (params?: Record<string, unknown>) => ['analytics', 'dropoff', params] as const,
    courses: (params?: Record<string, unknown>) => ['analytics', 'courses', params] as const,
    lectures: (params?: Record<string, unknown>) => ['analytics', 'lectures', params] as const,
    mcq: (params?: Record<string, unknown>) => ['analytics', 'mcq', params] as const,
    cq: (params?: Record<string, unknown>) => ['analytics', 'cq', params] as const,
    payments: (params?: Record<string, unknown>) => ['analytics', 'payments', params] as const,
    acquisition: (params?: Record<string, unknown>) => ['analytics', 'acquisition', params] as const,
    search: (params?: Record<string, unknown>) => ['analytics', 'search', params] as const,
    devices: (params?: Record<string, unknown>) => ['analytics', 'devices', params] as const,
    geo: (params?: Record<string, unknown>) => ['analytics', 'geo', params] as const,
    realtime: () => ['analytics', 'realtime'] as const,
    insights: (params?: Record<string, unknown>) => ['analytics', 'insights', params] as const,
    predictions: (params?: Record<string, unknown>) => ['analytics', 'predictions', params] as const,
    alerts: () => ['analytics', 'alerts'] as const,
    reports: () => ['analytics', 'reports'] as const,
  },
}
